node {
    
    // --------------------------- DO NOT PUSH CHANGES IN THE FOLLOWING SECTION -------------------------------------
	// --------------------------- -------------CONFIGURATION -------------------------------------------------------

    def FORGE_CREDENTIALS_ID = "forge-git-password"

    def pwd = ""
      
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
        checkout scm
    }

    stage('Install Dependencies') {
        withCredentials([
            usernamePassword(credentialsId: FORGE_CREDENTIALS_ID, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD'),
        ]){

            echo "$PASSWORD"
            pwd="$PASSWORD"

        }
    }

    stage('log') {
        echo "$pwd"
        echo "$env[$FORGE_CREDENTIALS_ID]"
        def cred = "$env[$FORGE_CREDENTIALS_ID]"
        echo "$cred['PASSWORD']"
    }
    
 


}