node {
    
    // --------------------------- DO NOT PUSH CHANGES IN THE FOLLOWING SECTION -------------------------------------
	// --------------------------- -------------CONFIGURATION -------------------------------------------------------

    def FORGE_CREDENTIALS_ID = "forge-git-password"

    def pwd = ""
    
    def id = ""
    def tenant =""
      
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
        checkout scm
    }

    stage('Install Dependencies') {
        withCredentials([azureServicePrincipal(servicePrincipalId)]){
        sh "az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID"
        pwd="$AZURE_CLIENT_SECRET"
        id="$AZURE_CLIENT_ID"
        tenant="$AZURE_TENANT_ID"
        }
    }

    stage('log') {
        echo "$pwd"
        echo "$id"
        echo "$tenant"
    }
    
 


}